### ISSUE TITLE
Slider thumbImage Issue

### ISSUE THREAD

**Issue by Cyberfolks** [barmej/react-native-youtube-player#13]
Error while updating property 'thumbImage' of a view managed by: RNCSlider

value for thumbImage cannot be cast from double to readablenativemap.

Testing on Real Device and Emulator. results are same. if you need screenshots.

**Comment by Cyberfolks** [comment]
is there any solution. i need urgent solution im waiting for your positive reply.

**Comment by Cyberfolks** [comment]
if you are unable to reply or can't fix issue so please remove your repo from npm. its wasted my time and maybe someone else face same issue... hope you will never mind and got my point.

**Comment by chandranshu12** [comment]
@Cyberfolks Ignoring your rude tone, may be check with react-native-slider guys.

**Comment by Cyberfolks** [comment]
@chandranshu12 thank you Chandranchu but its a major issue with this repo. i replied him after 11 days as you know developer have no enough time and its my responsibility to resolve issues if someone facing if im sharing my repo. and i tried by installing slider but failed. no doubt repo is out standing but im disappointed with @yjose  even sent him personal request by mailing issue.

**Comment by yjose** [comment]
Hi @Cyberfolks, We are using this package in our prod react-native app(0.59) and it works as expected.
Just coming from my leave a few days ago, and I don't have enough time to take a look at every issue so make sure to be kind asking for solutions.  

Regarding the issue with Slider, I think we are going to use react native gesture Handel to build a custom one, because the Community one is very limited and had some issues.

will try to start working on it ASAP.

**Comment by Cyberfolks** [comment]
> Hi @Cyberfolks, We are using this package in our prod react-native app(0.59) and it works as expected.
> Just coming from my leave a few days ago, and I don't have enough time to take a look at every issue so make sure to be kind asking for solutions.
> 
> Regarding the issue with Slider, I think we are going to use react native gesture Handel to build a custom one, because the Community one is very limited and had some issues.
> 
> will try to start working on it ASAP.

Thank You @yjose and sorry for my bad language.

**Comment by sagranatus** [comment]
npm install @react-native-community/slider@^1.1.2 solved that problem.

**Comment by ebrahimpleite** [comment]
some solution?

**Comment by shahzi8285** [comment]
you should really close this trash repo

**Comment by shahzi8285** [comment]
it wasted my 4 hours

**Comment by ebrahimpleite** [comment]
> it wasted my 4 hours

I solved it this way:

update the react-native-community / slider dependency on react-native-yt-player

**Comment by sushantklay** [comment]
Facing the same issue.

"@react-native-community/slider": "^2.0.9",
"react-native": "0.61.2",

Nothing seems to work. Any solutions?

**Comment by ebrahimpleite** [comment]
> Facing the same issue.
> 
> "@react-native-community/slider": "^2.0.9",
> "react-native": "0.61.2",
> 
> Nothing seems to work. Any solutions?

update the react-native-community / slider dependency on react-native-yt-player to 2.0.9 too.

**Comment by keyblade95** [comment]
I have the same error.. did you solve the issue?

**Comment by keyblade95** [comment]
I finally managed to solve the problem above with a simple workaround: I copied the entire src/mobile folder into my project. Then I installed the required dependencies:
```js
"dependencies": {
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-get-random-values": "^1.4.0",
    "@react-native-community/slider": "^2.0.9",
    "react-native-orientation": "^3.1.3",
    "react-native-reanimated": "^1.8.0",
    "react-native-webview": "^9.2.1",
    "react-native-webview-invoke": "^0.5.1"
}
```
Don't forget to remove the original react-native-yt-player from the dependencies!
At this point, I imported the player from the project folder! Everything should work correctly.
