### ISSUE TITLE
Tried to register two views with the same name RNCWebView

### ISSUE THREAD

**Issue by stefanosandes** [barmej/react-native-youtube-player#15]
I have r`eact-native-webview` as a dependency of my app, and I'm getting this error after install `react-native-youtube-player`. I think it is because my version of `RNCWebView` is different than your.

**Comment by sadez** [comment]
I think it must be updated to the latest webview (version 7.0.1 )version to also Remove UIWebView

**Comment by sheshnathiicmr** [comment]
@sadez +1

**Comment by fabripeco** [comment]
Same issue for me. The latest version of `react-native-webview` is 8.0.3. Maybe you can consider to move it as a peer dependencies in the same way as https://github.com/archriss/react-native-render-html did. Thank you!

**Comment by ivan-kalinin** [comment]
Same issue but with slider ` Tried to register two views with the same name RNCSlider`, the same version is  not working also.

**Comment by matthewadel** [comment]
navigate to nodeModules in react-native-yt-player, then delete folder named react-native-webrtc
that worked for me

**Comment by aviemore** [comment]
> navigate to nodeModules in react-native-yt-player, then delete folder named react-native-webrtc
> that worked for me

@matthewadel and what if you try reinstall modules `rm -rf node-modules && npm i`? I suppose you get the same issue again, it’s not a solution
