### ISSUE TITLE
Control panel buttons don't work...

### ISSUE THREAD

**Issue by Pikerstrow** [barmej/react-native-youtube-player#18]
Hello! Please, would you help to find the reason why control panel buttons doesn't work at all... Play, pause, fullscreen - no one of them. I've rechecked instalation manual twice and seems everything is correct.
My 'package.json':
"dependencies": {
    "@react-native-community/async-storage": "^1.8.0",
    "@react-native-community/masked-view": "^0.1.6",
    "@react-native-community/slider": "^1.1.2",
    "axios": "^0.19.2",
    "install": "^0.13.0",
    "jetifier": "^1.6.5",
    "moment": "^2.24.0",
    "native-base": "^2.13.8",
    "npm": "^6.13.7",
    "react": "16.8.3",
    "react-native": "0.59.8",
    "react-native-device-info": "^5.5.3",
    "react-native-fbsdk": "^1.1.2",
    "react-native-gesture-handler": "^1.6.0",
    "react-native-google-signin": "^2.1.1",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-orientation": "^3.1.3",
    "react-native-reanimated": "^1.7.0",
    "react-native-render-html": "^4.1.2",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.0.0-beta.10",
    "react-native-snap-carousel": "^3.8.4",
    "react-native-splash-screen": "^3.2.0",
    "react-native-status-bar-height": "^2.4.0",
    "react-native-svg": "^11.0.1",
    "react-native-vector-icons": "^6.6.0",
    "react-native-webview": "^5.10.0",
    "react-native-webview-invoke": "^0.5.0",
    "react-native-yt-player": "^1.0.6",
    "react-navigation": "^4.1.1",
    "react-navigation-stack": "^2.1.1",
    "react-navigation-tabs": "^2.7.0"
  },
  "devDependencies": {
    "@babel/core": "7.8.4",
    "@babel/runtime": "7.8.4",
    "babel-jest": "25.1.0",
    "jest": "25.1.0",
    "metro-react-native-babel-preset": "0.58.0",
    "react-test-renderer": "16.8.3"
  },

**Comment by joegichuru** [comment]
getting the same

**Comment by yjose** [comment]
same as #7
