### ISSUE TITLE
Please Pull Down this f**king library

### ISSUE THREAD

**Issue by shahzi8285** [barmej/react-native-youtube-player#23]
I have wasted my  3 hour with this trash there is error after error..I request you to pls take this down so that other dont waste thier time

**Comment by yjose** [comment]
Hi @shahzi8285 , 

Most of the issue is Related to React Native Slider, I am almost done working on a new Implementation of Video controls using gesture handler with reanimated API. 

Please Make sure to use kind words next time, and would love if you can report those issues.
