### ISSUE TITLE
Custom Style not overriding default style

### ISSUE THREAD

**Issue by ngouass** [barmej/react-native-youtube-player#30]
Hi, I didn't succeed to adjust the size of the Player and while looking at the code, it seems that the custom style is not take into account.

[Player-Render-Function](https://github.com/barmej/react-native-youtube-player/blob/977f582bcd9015b425d15af4bd5698d2896f0b6e/src/mobile/Player.tsx#L203)

**Comment by hitesh25kumar** [comment]
Same issue
